#!/bin/bash

# Eesnimede väljatrükk
# 1. Lõikame välja teise välja (eesnimi) kasutades 'cut' ja eraldajaks on " "
# 2. Seejärel lõikame välja esimese osa, mis on enne ";" (kui see on olemas)
# 3. Muudame suured tähed väikesteks 'sed' käsku kasutades, et muuta iga suur täht väikeseks
cut -f2 -d" " inimesed.txt | cut -f1 -d";" | sed 's/[A-Z]/\L&/g' > eesnimed.txt

# Perekonnanimede väljatrükk
# 1. Lõikame välja teise välja (perekonnanimi) kasutades 'cut' ja eraldajaks on ":"
# 2. Seejärel lõikame välja esimese osa, mis on enne "," (kui see on olemas)
# 3. Muudame suured tähed väikesteks 'sed' käsku kasutades, et muuta iga suur täht väikeseks
cut -f2 -d":" inimesed.txt | cut -f1 -d"," | sed 's/[A-Z]/\L&/g' > perenimed.txt

# Domeenide väljatrükk
# 1. Lõikame välja teise osa, mis on pärast "-" (domeen) kasutades 'cut'
# 2. Lõikame välja osa, mis on enne " " (tühikut), et saada domeeni
# 3. Muudame suured tähed väikesteks 'sed' käsku kasutades, et muuta iga suur täht väikeseks
cut -f2 -d"-" inimesed.txt | cut -f1 -d" " | sed 's/[A-Z]/\L&/g' > domeenid.txt

# Kasutajanimede loomine
# 1. Ühendame eesnimed ja perekonnanimed punktiga kasutades 'paste'
# 2. Tulemuseks on fail, kus iga kasutajanimi on vormistatud eesnime ja perekonnanime kombinatsioonina
paste -d"." eesnimed.txt perenimed.txt > kasutajad.txt

# E-mailide loomine
# 1. Ühendame kasutajanimed ja domeenid '@' märkiga
# 2. Tulemuseks on fail, kus iga e-mail on vormistatud kujul "kasutajanimi@domeen"
paste -d"@" kasutajad.txt domeenid.txt > meilid.txt

# Kuvame loodud failide nimed
# 1. Prindime ekraanile, kus asuvad iga genereeritud faili nimed
echo "Eesnimed salvestatud faili: eesnimed.txt"
echo "Perekonnanimed salvestatud faili: perenimed.txt"
echo "Domeenid salvestatud faili: domeenid.txt"
echo "Kasutajatunnused salvestatud faili: kasutajad.txt"
echo "E-mailid salvestatud faili: meilid.txt"
