#!/bin/bash

# Määrame kausta, kus käib töö
current_dir=$(pwd)

# Kontrollime, kas antud kaust on Git repoga kaust
if [ ! -d ".git" ]; then
    echo "See kaust ei ole Git repoga kaust. Palun initsialiseeri Git repo."
    exit 1
fi

# Kontrollige, kas git on installitud
if ! command -v git &> /dev/null
then
    echo "Git ei ole installitud."
    exit 1
fi

# Lisame kõik muudatused Git-i
git add .

# Teeme commit'i
commitMessage="Automatiseeritud üleslaadimine skriptist $(basename "$current_dir")"
git commit -m "$commitMessage"

# Lükka muudatused GitHubi (kasutame SSH autentimist)
repoUrl="git@github.com:Adrian69420N/skriptimine.git"
git push -uf "$repoUrl" master

echo "Skript üles laetud GitHubi edukalt kaustast $current_dir"
