#!/bin/bash
# Skript, mis küsib kuu numbrit ja väljastab aastaaja

read -p "Sisesta kuu number: " kuu

if [ $kuu -eq 12 ] || [ $kuu -le 2 ]; then
    echo "Praegu on talv"
elif [ $kuu -ge 3 -a $kuu -le 5 ]; then
    echo "Praegu on kevad"
elif [ $kuu -ge 6 -a $kuu -le 8 ]; then
    echo "Praegu on suvi"
elif [ $kuu -ge 9 -a $kuu -le 11 ]; then
    echo "Praegu on sügis"
else
    echo "Vigane kuu number"
fi
