#!/bin/bash
#See skript tervitab kasutajat tema nimega

#Valjastame tere ilma reavahetuseta
echo -n "Tere, "

#Tekitame kasutajanime, mis kuvatakse suure tahega
kasutajanimi=$(whoami)
echo -n "$(echo ${kasutajanimi^})"

#Valjastame kasutaja nime ilma reavahetuseta
echo -n "$username"

#Valjastame "!" reavahetusega
echo "!"
