#!/bin/bash
#See skript tervitab kasutajat tema nimega

#Valjastame tere ilma reavahetuseta
echo -n "Tere, "

#Leiame kasutajanime
username=$(whoami)
#Valjastame kasutaja nime ilma reavahetuseta
echo -n "$username"

#Valjastame "!" reavahetusega
echo "!"
